on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - run: |
        dep=true
        if $dep ; then 
        echo "::warning::Deprecated function found"
        fi
    - name: Set API key
      run: echo "API_KEY=12345" >> $GITHUB_ENV
      
    - name: Use API key
      run: echo "Using API key $API_KEY"

    - name: Check if a file exsist
      run: |
        if [-f "config.yml"]; then
        echo"::debug::config.yml exsists"
        else
          echo "::error::config.yml is missing"
        fi

    - name: Use API key
      run: |
          echo "::add-mask::$API_KEY"
          echo "Using API key $API_KEY"
